---
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
    theme: spacelab           # flatly spacelab sandstone cerulean
    code_download: true
runtime: shiny
---


```{r run ToxicR, echo = FALSE,warning = FALSE, message = FALSE, progress = FALSE} 

source("~/storage/qPCR Analysis/qPCR analysis Script.R", local = TRUE)

#source("~/storage/R-ODAF_Health_Canada/ToxicR workinprogress.R", local = TRUE)
```

```{r generate_table}
DT::datatable(CTdf,
          options = list(pagingType = 'full_numbers',
                         pageLength = 20,
                         scrollX = '100%',
                         dom = 'Bfrtip',
                         buttons = c('copy',
                                     'csv',
                                     'excel',
                                     'pdf',
                                     'print',
                                     'colvis'),
                         digits=3),
          escape = FALSE,
          extensions = 'Buttons',
          rownames = ,
          filter = "top",
          )
```

```{r render_plot}
library(shiny)

server <- function(input, output,session) {
  observe({
    # Update choices for selectGene based on selectedChemical
    updateSelectInput(session, "selectGene", choices = unique(CTdf[CTdf$chemicalgroup == input$selectChemical, "gene"]))
  })
  selection <- reactive({
    selected_chemical <-input$selectChemical
    selected_gene <- input$selectGene
    subset_table <- CTdf %>%
      filter(chemicalgroup == selected_chemical, gene == selected_gene)
    subset_table$concentration <- as.numeric(gsub("[^0-9]", "", sapply(strsplit(subset_table$chemical, " "), "[", 1)))
    subset_table <- subset_table[order(subset_table$concentration), ]
    plot <- ggplot(subset_table, aes(x = fct_inorder(chemical), y = average_RQ)) +
      geom_bar(stat = "identity", fill = "grey", color = "black", width = 0.7) +
      geom_errorbar(aes(ymin = average_RQ - SEM, ymax = average_RQ + SEM), width = 0.25, position = position_dodge(0.7)) +
      labs(title =g, x = "Chemical Concentration", y = "Fold Change") + 
      theme_bw()
  })
  output$plot <- renderPlot({
    plot <- selection()
    print(plot)
  })
}

ui <- fluidPage(
  selectInput(inputId = "selectChemical", label = "Chemical", choices = unique(CTdf$chemicalgroup)),
  selectInput(inputId = "selectGene", label = "Gene", choices = NULL),
  #plotOutput("my_plot"),
  plotOutput("plot"),  # Display the selected column as text
)

shinyApp(ui = ui, server = server)




```